usage: argparse_help_to_md [-h] [--encoding ENCODING] input output

Converts a help info to a standard documentation

positional arguments:
  input                Path to a text file containing the help generated by a Python script using argparse.
  output               Output .md file

optional arguments:
  -h, --help           show this help message and exit
  --encoding ENCODING  Specify the encoding of the input file

Example:
 * With Windows

```
python ./myscript --help | Out-File -FilePath myscript_help.txt
python ./argparse_help_to_md myscript_help.txt Readme.md
```

 * With Linux
```
python myscript --help > myscript_help.txt
python argparse_help_to_md myscript_help.txt Readme.md
```
